### ISSUE TITLE
Non-embedded icon

### ISSUE THREAD

**Issue by myself600** [07th-mod/ponscripter-fork#13]
The `GAME` variable is used to embed the icon into the executable, which isn't optimal since the engine is shared between games. Would it be possible to change this so that it picks up the icon from the game folder just like with Ren'Py?

**Comment by drojf** [comment]
I'm not sure if this answers your question, but you can change the icon by changing the `default.icns`, `default.ico`, and `default.png` files in the [`src/resources`](https://github.com/07th-mod/ponscripter-fork/tree/mod/src/resources)  folder 

----

If you're using our github actions script to build, it still has some Umineko specific stuff in it (my fault) like having copies of the exe for question and answer, and I was supposed to fix it as described in issue https://github.com/07th-mod/ponscripter-fork/issues/11, but I just hadn't got around to it. 

If you're going to be using it however, I'd definitely want to fix it for you.

**Comment by myself600** [comment]
I'm building distribution specific packages from source and there's a separate package for the engine and the game, so the icon is stored outside ponscripter

**Comment by TellowKrinkle** [comment]
I assume that means the exe itself would have the wrong icon, but the app would change the one displayed in the taskbar after launching?

Would you want to do that with a script command?

**Comment by TellowKrinkle** [comment]
Actually, maybe it would be better as a command line option?  Then you don't have to modify the game script to set it.  I assume you're launching programmatically, since otherwise the user would be able to see the (wrong) exe icon.

**Comment by TellowKrinkle** [comment]
Hmm it looks like it's already set up to load an icon named `icon.png`, though that looks like it's from the cwd instead of the game root dir or something like that.  Does that work for you?

https://github.com/07th-mod/ponscripter-fork/blob/a39f9b659abdc152925d8bc3ac27a83ef53eeac1/src/PonscripterLabel.cpp#L518

**Comment by myself600** [comment]
> Does that work for you?

Yes, thanks!
