### ISSUE TITLE
Version string in release packages

### ISSUE THREAD

**Issue by myself600** [07th-mod/ponscripter-fork#15]
Please consider using versioned filenames as is usually the standard. This is causing issues when building packages on Arch as files with identical names are only downloaded once (https://wiki.archlinux.org/title/PKGBUILD#Sources - red warning box) and this can only be circumvented using ugly hacks (moving `source` array to `build()` function).

**Comment by drojf** [comment]
Hopefully this is OK?

https://github.com/07th-mod/ponscripter-fork/releases/tag/v3.0.2

**Comment by myself600** [comment]
Yes, thanks!

The idea is to avoid situations when an update comes out but it's not being downloaded as the older version with the same filename is still cached on the disk, thus the package appears to be updated but in reality it isn't

**Comment by drojf** [comment]
> The idea is to avoid situations when an update comes out but it's not being downloaded as the older version with the same filename is still cached on the disk, thus the package appears to be updated but in reality it isn't

I've...personally encountered this problem myself with our mod and files hosted on our own server so I understand completely.
