### ISSUE TITLE
Increased font size on save/load screen

### ISSUE THREAD

**Issue by drojf** [07th-mod/ponscripter-fork#2]
The new executable has increased text size on the save/load screen, which causes the text to escape the buttons. 

Later I should check how the text is drawn so it's easier to identify what's happening here.

Original
![Capture](https://user-images.githubusercontent.com/1249449/106370618-c3c7a600-63af-11eb-8e6a-6b8a2b34a41d.JPG)

New Executable
![Capture2](https://user-images.githubusercontent.com/1249449/106370620-c924f080-63af-11eb-914b-9442b1bbab82.JPG)

**Comment by andOlga** [comment]
This was "fixed" (or, rather, re-broken) by d2b5d190477c0b32bd0aca87972a5c047c1ef451.
